# prefix for the container names
# if empty, the container name will be [username]-[instance], 
# otherwise, [prefix]-[username]-[instance]. e.g. "pd" -> pd-[username]-[instance]
name_prefix = "pd"

# should be comma-separated list of ports or ranges
# e.g. "20000,20002-20010"
available_ports = "20000-21000"

# the name of the user committed image
# the actual image name will be [commit_name]:[username] or [commit_name]:[username]-[tag]
commit_name = "pody-commit"
commit_image_ports = [22, 8000]

volume_mappings = [
	"/data/pody-volume/$username:/workspace/$username:rw", 
	"/data/pody-volume/share:/workspace/share:ro", 
	"tmpfs:/workspace/tmpfs", 	# tmpfs mount, remove this line if you do not want tmpfs mounts
]

# the name of the network to be created for the containers
# should manually create the network before using it
# if empty, the default bridge network will be used
network = ""

# fallback quota for unspecified user-quota
# ["" for string] and [-1 for integer] means no limit ("none" for gpus means no gpu)
[default_quota]
max_pods = 5
gpu_count = -1
gpus = "all"
memory_limit = '64g'
storage_size = ''
commit_count = 1
commit_size_limit = '20g'
shm_size = '8g'
tmpfs_size = '1g'  			# set to 'none' for no tmpfs mount

# Below are the images that will be exposed to the user, 
# please configure them according to available images in the system
# the ports will be mapped to the host machine under random available port
# if tag is not specified, all tags of the image will be available
[[images]]
name = "ubuntu2204-cu121-base:latest"
ports = [22, 8000]

[[images]]
name = "lab-cuda"
ports = [22]
